server:
  port: 8182

spring:
  rabbitmq:
    host: 192.168.0.109
    port: 5672
    username: admin
    password: 123
    publisher-confirm-type: correlated # 这个配置没生效，不知道为什么
    publisher-confirms: true
    publisher-returns: true